#!/Users/axelberger/Ex_vscode/Venv_quantum/code_python/env_new/bin/python3
import sys
from fontTools.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
